import React, { createContext, useContext, useState } from 'react'

const translations = {
  fr: {
    nav: {
      solution: 'Solution',
      product: 'Produit',
      technology: 'Technologie',
      ai: 'SenDon-AI',
      recognition: 'Distinctions',
      contact: 'Contact',
    },
    hero: {
      badge: 'Plateforme nationale de don de sang',
      title: 'Quand le sang est nécessaire, le temps ne doit pas décider',
      titleHighlight: 'qui vit',
      subtitle: 'SenDon connecte intelligemment donneurs, hôpitaux et CNTS en temps réel — pour que chaque vie compte.',
      ctaPrimary: 'Découvrir la plateforme',
      ctaSecondary: 'Voir le fonctionnement',
      stat1: 'Donneurs actifs',
      stat2: 'Hôpitaux connectés',
      stat3: 'Vies sauvées',
      stat4: 'Villes couvertes',
    },
    problem: {
      badge: 'Le Problème',
      title: 'Une crise silencieuse au cœur du système de santé',
      subtitle: 'Chaque année, des milliers de patients meurent par manque de sang disponible au bon moment, au bon endroit.',
      card1Title: 'Pénuries critiques',
      card1Desc: 'Les hôpitaux manquent de sang chaque jour, sans visibilité sur les stocks disponibles dans les centres voisins.',
      card2Title: 'Coordination absente',
      card2Desc: 'Aucun lien direct entre donneurs volontaires, établissements de soins et le CNTS pour une gestion efficace.',
      card3Title: 'Urgences non gérées',
      card3Desc: 'En cas d\'urgence, les soignants perdent un temps précieux à rechercher manuellement des compatibilités.',
      card4Title: 'Données fragmentées',
      card4Desc: 'Les données sur les stocks, besoins et donneurs ne sont pas centralisées ni exploitables en temps réel.',
    },
    solution: {
      badge: 'La Solution',
      title: 'Une plateforme unifiée, intelligente et humaine',
      subtitle: 'SenDon crée un écosystème connecté où chaque acteur dispose des outils et données nécessaires pour agir vite et bien.',
      feature1: 'Alertes en temps réel',
      feature1Desc: 'Notifications intelligentes aux donneurs compatibles dans un rayon géographique défini.',
      feature2: 'Matching IA',
      feature2Desc: 'Algorithme de correspondance sang/patient optimal basé sur groupe, Rhésus et urgence.',
      feature3: 'Tableau de bord CNTS',
      feature3Desc: 'Vision nationale des stocks, flux et besoins pour une décision stratégique instantanée.',
      feature4: 'Mobile-first',
      feature4Desc: 'Application intuitive accessible à tous les donneurs, même dans les zones à faible connectivité.',
    },
    interactive: {
      badge: 'Le Produit',
      title: 'Une expérience pensée pour chaque acteur',
      subtitle: 'Découvrez comment SenDon transforme le quotidien de chaque partie prenante.',
      tabs: {
        donor: 'Donneur',
        hospital: 'Hôpital',
        cnts: 'CNTS',
      },
      donor: {
        title: 'L\'expérience Donneur',
        subtitle: 'Simple, humaine et impactante',
        feature1: 'Alertes intelligentes',
        feature1Desc: 'Recevez une notification quand un patient compatible a besoin de vous à proximité.',
        feature2: 'Réponse en un clic',
        feature2Desc: 'Confirmez votre disponibilité en moins de 5 secondes depuis votre smartphone.',
        feature3: 'Matching géolocalisé',
        feature3Desc: 'Soyez mis en relation avec l\'hôpital le plus proche ayant un besoin urgent.',
        feature4: 'Historique & suivi',
        feature4Desc: 'Suivez votre impact et planifiez vos prochains dons en toute sérénité.',
      },
      hospital: {
        title: 'L\'interface Hôpital',
        subtitle: 'Efficacité, rapidité et contrôle',
        feature1: 'Création de demandes',
        feature1Desc: 'Soumettez une demande d\'urgence en quelques clics avec tous les détails nécessaires.',
        feature2: 'Suivi en temps réel',
        feature2Desc: 'Visualisez l\'état des demandes, les donneurs en route et les stocks disponibles.',
        feature3: 'Coordination CNTS',
        feature3Desc: 'Communication directe et automatisée avec le CNTS pour les demandes critiques.',
        feature4: 'Historique complet',
        feature4Desc: 'Accédez à l\'historique de toutes les transfusions et donneurs ayant contribué.',
      },
      cnts: {
        title: 'Le Dashboard CNTS',
        subtitle: 'Stratégique, institutionnel et intelligent',
        feature1: 'Supervision nationale',
        feature1Desc: 'Vue d\'ensemble en temps réel de tous les stocks et flux de sang à l\'échelle nationale.',
        feature2: 'Analyse des données',
        feature2Desc: 'Rapports détaillés sur les tendances, pénuries prévisionnelles et zones à risque.',
        feature3: 'Aide à la décision',
        feature3Desc: 'Recommandations de l\'IA pour optimiser la distribution et anticiper les besoins.',
        feature4: 'Heatmap nationale',
        feature4Desc: 'Visualisation géographique des zones de tension et des centres les plus actifs.',
      },
    },
    ai: {
      badge: 'SenDon-AI',
      title: 'Une intelligence qui sauve des vies avant même l\'urgence',
      subtitle: 'Notre moteur d\'IA prédit les pénuries, optimise la distribution et guide les décisions stratégiques du CNTS.',
      feature1: 'Prédiction des pénuries',
      feature1Desc: 'Anticipez les pénuries de sang jusqu\'à 14 jours à l\'avance grâce à nos modèles prédictifs.',
      feature2: 'Aide à la décision',
      feature2Desc: 'Recommandations automatiques pour redistribuer les stocks entre établissements.',
      feature3: 'Heatmap nationale',
      feature3Desc: 'Visualisation en direct des zones à risque et des besoins urgents sur la carte nationale.',
      feature4: 'Analyse prédictive',
      feature4Desc: 'Modèles entraînés sur des données historiques pour une précision de prédiction optimale.',
    },
    awards: {
      badge: 'Distinctions & Reconnaissances',
      title: 'Reconnus par les leaders mondiaux de la HealthTech',
      subtitle: 'Notre vision a été validée par les plus grandes organisations d\'innovation en santé mondiale.',
      award1Name: '2ème Prix d\'Excellence Nationale',
      award1Org: 'Gov\'athon 2025',
      award1Year: '2025',
      award1Desc: 'Sélectionné parmi 840 projets nationaux, SenDon se distingue par son fort impact social, sa capacité à améliorer l’accès aux soins dans le service public et son approche IA innovante au service de la prise de décision du CNTS.',
      award2Name: '1er Prix Hackathon AMREF-UIDT',
      award2Org: 'Amref Health Africa - UIDT',
      award2Year: '2025',
      award2Desc: 'SenDon se voit décerner le 1er prix du Hackathon AMREF-UIDT pour sa solution innovante de gestion intelligente du don de sang.',
      award3Name: '1er Prix Hackathon DocSen',
      award3Org: 'DocSen',
      award3Year: '2025',
      award3Desc: 'Reconnu encore une fois parmi les meilleures innovations en santé numérique pour notre plateforme SenDon.',
    },
    technology: {
      badge: 'Technologie',
      title: 'Une architecture de classe mondiale',
      subtitle: 'Construite pour la scalabilité, la fiabilité et la performance en temps réel.',
      t1: 'Microservices',
      t1Desc: 'Architecture modulaire permettant une mise à l\'échelle indépendante de chaque service.',
      t2: 'Temps réel',
      t2Desc: 'WebSockets et événements push pour des mises à jour instantanées sur toute la plateforme.',
      t3: 'Cloud Native',
      t3Desc: 'Déploiement Kubernetes multi-région pour une disponibilité de 99.9%.',
      t4: 'Sécurité avancée',
      t4Desc: 'Chiffrement de bout en bout et conformité RGPD pour la protection des données patients.',
      t5: 'IA embarquée',
      t5Desc: 'Modèles ML entraînés localement pour une inférence rapide et des données souveraines.',
      t6: 'API ouverte',
      t6Desc: 'REST et GraphQL pour une intégration facile avec les systèmes hospitaliers existants.',
    },
    footer: {
      tagline: 'Connecter des vies, sauver des vies.',
      product: 'Produit',
      company: 'Entreprise',
      legal: 'Légal',
      links: {
        solution: 'La Solution',
        ai: 'SenDon-AI',
        hospital: 'Interface Hôpital',
        donor: 'Espace Donneur',
        about: 'À propos',
        blog: 'Blog',
        press: 'Presse',
        careers: 'Carrières',
        privacy: 'Confidentialité',
        terms: 'Conditions d\'utilisation',
        security: 'Sécurité',
      },
      copy: '© 2025 SenDon. Tous droits réservés.',
    },
  },
  en: {
    nav: {
      solution: 'Solution',
      product: 'Product',
      technology: 'Technology',
      ai: 'SenDon-AI',
      recognition: 'Awards',
      contact: 'Contact',
    },
    hero: {
      badge: '#1 HealthTech Platform in Senegal',
      title: 'When Blood is Needed, Time Should Not Decide',
      titleHighlight: 'Who Lives',
      subtitle: 'SenDon intelligently connects donors, hospitals and CNTS in real time — so every life matters.',
      ctaPrimary: 'Explore the Platform',
      ctaSecondary: 'See How It Works',
      stat1: 'Active Donors',
      stat2: 'Connected Hospitals',
      stat3: 'Lives Saved',
      stat4: 'Cities Covered',
    },
    problem: {
      badge: 'The Problem',
      title: 'A silent crisis at the heart of the healthcare system',
      subtitle: 'Every year, thousands of patients die due to lack of available blood at the right time, in the right place.',
      card1Title: 'Critical shortages',
      card1Desc: 'Hospitals run out of blood every day, with no visibility into available stocks at nearby centers.',
      card2Title: 'Missing coordination',
      card2Desc: 'No direct link between voluntary donors, healthcare facilities, and the CNTS for effective management.',
      card3Title: 'Unmanaged emergencies',
      card3Desc: 'In emergencies, caregivers waste precious time manually searching for compatible blood types.',
      card4Title: 'Fragmented data',
      card4Desc: 'Data on stocks, needs, and donors is not centralized or exploitable in real time.',
    },
    solution: {
      badge: 'The Solution',
      title: 'A unified, intelligent and human platform',
      subtitle: 'SenDon creates a connected ecosystem where every actor has the tools and data needed to act fast and well.',
      feature1: 'Real-time alerts',
      feature1Desc: 'Smart notifications to compatible donors within a defined geographic radius.',
      feature2: 'AI Matching',
      feature2Desc: 'Optimal blood/patient matching algorithm based on blood type, Rh factor, and urgency.',
      feature3: 'CNTS Dashboard',
      feature3Desc: 'National view of stocks, flows, and needs for instant strategic decision-making.',
      feature4: 'Mobile-first',
      feature4Desc: 'Intuitive app accessible to all donors, even in low-connectivity areas.',
    },
    interactive: {
      badge: 'The Product',
      title: 'An experience designed for every stakeholder',
      subtitle: 'Discover how SenDon transforms the daily life of each key player.',
      tabs: {
        donor: 'Donor',
        hospital: 'Hospital',
        cnts: 'CNTS',
      },
      donor: {
        title: 'The Donor Experience',
        subtitle: 'Simple, human and impactful',
        feature1: 'Smart alerts',
        feature1Desc: 'Receive a notification when a compatible patient needs you nearby.',
        feature2: 'One-click response',
        feature2Desc: 'Confirm your availability in less than 5 seconds from your smartphone.',
        feature3: 'Geolocated matching',
        feature3Desc: 'Be connected to the nearest hospital with an urgent need.',
        feature4: 'History & tracking',
        feature4Desc: 'Track your impact and plan your next donations with peace of mind.',
      },
      hospital: {
        title: 'The Hospital Interface',
        subtitle: 'Efficiency, speed and control',
        feature1: 'Request creation',
        feature1Desc: 'Submit an emergency request in a few clicks with all necessary details.',
        feature2: 'Real-time tracking',
        feature2Desc: 'Visualize request status, donors en route, and available stocks.',
        feature3: 'CNTS coordination',
        feature3Desc: 'Direct and automated communication with CNTS for critical requests.',
        feature4: 'Complete history',
        feature4Desc: 'Access the full history of all transfusions and contributing donors.',
      },
      cnts: {
        title: 'The CNTS Dashboard',
        subtitle: 'Strategic, institutional and intelligent',
        feature1: 'National oversight',
        feature1Desc: 'Real-time overview of all blood stocks and flows at the national level.',
        feature2: 'Data analysis',
        feature2Desc: 'Detailed reports on trends, projected shortages, and at-risk areas.',
        feature3: 'Decision support',
        feature3Desc: 'AI recommendations to optimize distribution and anticipate needs.',
        feature4: 'National heatmap',
        feature4Desc: 'Geographic visualization of tension zones and most active centers.',
      },
    },
    ai: {
      badge: 'SenDon-AI',
      title: 'An intelligence that saves lives before the emergency',
      subtitle: 'Our AI engine predicts shortages, optimizes distribution, and guides CNTS strategic decisions.',
      feature1: 'Shortage prediction',
      feature1Desc: 'Anticipate blood shortages up to 14 days in advance with our predictive models.',
      feature2: 'Decision support',
      feature2Desc: 'Automatic recommendations for redistributing stocks between facilities.',
      feature3: 'National heatmap',
      feature3Desc: 'Live visualization of at-risk zones and urgent needs on the national map.',
      feature4: 'Predictive analysis',
      feature4Desc: 'ML models trained on historical data for optimal prediction accuracy.',
    },
    awards: {
      badge: 'Awards & Recognition',
      title: 'Recognized by global HealthTech leaders',
      subtitle: 'Our vision has been validated by the greatest global health innovation organizations.',
      award1Name: '2nd Prize of Excellence',
      award1Org: 'Gov\'athon 2025',
      award1Year: '2025',
      award1Desc: 'Selected from 840 national projects, SenDon stood out for its social impact, the quality of its solution to improve access to healthcare in the public service, and its AI-based approach, which supports the CNTS in decision-making.',
      award2Name: 'Winner – Digital Health Challenge Africa',
      award2Org: 'WHO African Region',
      award2Year: '2025',
      award2Desc: 'Selected among 200+ African startups for our unique intelligent blood donation management solution.',
      award3Name: 'Finalist – International HealthTech Competition',
      award3Org: 'Global Health Innovation Summit',
      award3Year: '2025',
      award3Desc: 'Recognized among the top 10 global digital health innovations for our SenDon platform.',
    },
    technology: {
      badge: 'Technology',
      title: 'A world-class architecture',
      subtitle: 'Built for scalability, reliability, and real-time performance.',
      t1: 'Microservices',
      t1Desc: 'Modular architecture enabling independent scaling of each service.',
      t2: 'Real-time',
      t2Desc: 'WebSockets and push events for instant updates across the entire platform.',
      t3: 'Cloud Native',
      t3Desc: 'Multi-region Kubernetes deployment for 99.9% availability.',
      t4: 'Advanced security',
      t4Desc: 'End-to-end encryption and GDPR compliance for patient data protection.',
      t5: 'Embedded AI',
      t5Desc: 'Locally trained ML models for fast inference and data sovereignty.',
      t6: 'Open API',
      t6Desc: 'REST and GraphQL for easy integration with existing hospital systems.',
    },
    footer: {
      tagline: 'Connecting lives, saving lives.',
      product: 'Product',
      company: 'Company',
      legal: 'Legal',
      links: {
        solution: 'The Solution',
        ai: 'SenDon-AI',
        hospital: 'Hospital Interface',
        donor: 'Donor Space',
        about: 'About Us',
        blog: 'Blog',
        press: 'Press',
        careers: 'Careers',
        privacy: 'Privacy Policy',
        terms: 'Terms of Use',
        security: 'Security',
      },
      copy: '© 2025 SenDon. All rights reserved.',
    },
  },
}

type Lang = 'fr' | 'en'
type Translations = typeof translations.fr

interface LangContextValue {
  lang: Lang
  toggleLang: () => void
  t: Translations
}

const LanguageContext = createContext<LangContextValue | undefined>(undefined)

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [lang, setLang] = useState<Lang>('fr')
  const t = translations[lang]
  const toggleLang = () => setLang(l => l === 'fr' ? 'en' : 'fr')
  return (
    <LanguageContext.Provider value={{ lang, toggleLang, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLang(): LangContextValue {
  const ctx = useContext(LanguageContext)
  if (!ctx) throw new Error('useLang must be used inside LanguageProvider')
  return ctx
}
